### ISSUE TITLE
Error after jekyll serve

### ISSUE THREAD

**Issue by maya** [maban/styleguide#1]
Hi there,

This is the error I'm getting after running `jekyll serve`:

Configuration file: /Users/maya/Code/styleguide/_config.yml
            Source: .
       Destination: ./_site
      Generating...
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:46: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:46: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:46: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/convertible.rb:46: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/tags/include.rb:147: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/tags/include.rb:147: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/tags/include.rb:147: warning: Unsupported encoding nil ignored
/Users/maya/.gem/ruby/2.0.0/gems/jekyll-2.4.0/lib/jekyll/tags/include.rb:147: warning: Unsupported encoding nil ignored
                    done.
 Auto-regeneration: enabled for '.'
Configuration file: /Users/maya/Code/styleguide/_config.yml
    Server address: http://0.0.0.0:4000//
  Server running... press ctrl-c to stop.

Do you know how we can resolve this?

Thanks,
Maya

**Comment by maya** [comment]
We resolved the issue. There was a jekyll configuration file that was malformed. Timezone and encoding both had `nil` as values and jekyll does not accept those values (for Ruby 2.0 and up). Thanks for the help @hugo491.

**Comment by maban** [comment]
Aghh! I would have never guessed that! But I've been messing about with it for a couple of hours and it still doesn't work locally for me :(
@maya – what's in your new config file? I've tried what you suggested but no luck. I'm wondering if it's to do with switching to Yosemite, because it worked fine locally before, and it works on GitHub pages (it's exactly the same code).

**Comment by maya** [comment]
@maban Ahh I do have Yosemite too! I guess that's why you're supposed to wait a year or so before updating OS.

Re: the new config file - I've changed encoding to utf-8 and for timezone you can use something from  IANA Time Zone Database, or I just commented it out (I think it should default to your local timezone).

And me too, even though the errors were resolved I still can't get it to compile locally.

**Comment by maban** [comment]
So does it work locally for you? I was going to give my computer a fresh OS install because I know there are some problems with it that might be related, but if it still doesn't work for you, I'll give the code another look.

**Comment by maya** [comment]
Nope, it doesn't work (locally or live on gh-pages).

**Comment by maya** [comment]
I'm curious if this ever got resolved?

**Comment by maban** [comment]
I hadn't forgotten about it, but it has been slipping down my to-do list. I spent quite a few hours fruitlessly trying to figure it out, and decided to re-build it from scratch to make sure it's a Jekyll bug rather than one of my own (which is more likely).

It's just weird it was working fine and suddenly not, despite not changing anything, and I see exactly the same thing you're seeing. I'll pick this up over the holidays.

**Comment by maban** [comment]
@maya, sorry this took so long to fix – want to try it out now?

Have a read of the commit description and the issue link in it because that will explain what the problem was and why I think this fix isn't ideal, but it'll do for now until I someone from Jekyll can get back to me with what I'm doing wrong, or what Jekyll is doing wrong.

**Comment by maya** [comment]
Looking good @maban! It works for me now. 

That's so funny that it was the issue of missing the front matter. I think that in order for Jekyll to process the file, it needs the front-matter in there, so that is really interesting that it worked without it before. The Jekyll docs say it's perfectly fine to leave nothing between the triple dashes, as front matter variables are optional: http://jekyllrb.com/docs/frontmatter/. 

Glad this got figured out!

**Comment by maban** [comment]
Yeah, the documentation threw me: https://github.com/jekyll/jekyll-help/issues/223#issuecomment-68677588
